# Generated by Django 3.0.5 on 2023-03-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blood_quantity',
            fields=[
                ('hopital_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bg_O_pos', models.IntegerField()),
                ('bg_O_neg', models.IntegerField()),
                ('bg_B_pos', models.IntegerField()),
                ('bg_B_neg', models.IntegerField()),
                ('bg_A_pos', models.IntegerField()),
                ('bg_A_neg', models.IntegerField()),
                ('bg_AB_pos', models.IntegerField()),
                ('bg_AB_neg', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hospital_address',
            fields=[
                ('hopital_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('city_area', models.CharField(max_length=40)),
                ('landmark', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_details',
            fields=[
                ('id_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('contact_no1', models.CharField(max_length=12)),
                ('contact_no2', models.CharField(blank=True, max_length=13, null=True)),
                ('blood_quant', models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='hospital_app.blood_quantity')),
                ('location', models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='hospital_app.hospital_address')),
            ],
        ),
    ]
