# Generated by Django 3.0.5 on 2023-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_auto_20230325_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='hospital_details',
            name='id_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
