# Generated by Django 3.0.5 on 2023-03-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_auto_20230325_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_address',
            old_name='city_area',
            new_name='address',
        ),
    ]
