# Generated by Django 3.0.5 on 2023-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_auto_20230325_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_quantity',
            name='last_updated',
            field=models.DateField(null=True),
        ),
    ]
