# Generated by Django 3.0.5 on 2023-04-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_blood_quantity_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_quantity',
            name='hopital_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital_address',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital_address',
            name='hopital_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital_details',
            name='id_no',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
