# Generated by Django 3.0.5 on 2023-04-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0006_auto_20230411_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_address',
            old_name='hopital_id',
            new_name='hospital_id',
        ),
    ]
