# Generated by Django 3.0.5 on 2023-04-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0007_auto_20230417_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_quantity',
            old_name='hopital_id',
            new_name='hospital_id',
        ),
    ]
