# Generated by Django 3.0.5 on 2023-03-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donor_app', '0009_donor_details_health'),
        ('hospital_app', '0004_auto_20230325_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment_scheduled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scheduled', models.DateField()),
                ('date_of_appointment', models.DateField()),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor_app.donor_details')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.hospital_details')),
            ],
        ),
    ]
