# Generated by Django 3.0.5 on 2023-03-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0009_donor_details_health'),
        ('patient_app', '0005_auto_20230328_1749'),
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blood_request',
            fields=[
                ('appointment_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date_of_request', models.DateField()),
                ('hospital_id', models.CharField(max_length=30)),
                ('recieved', models.BooleanField(default=False)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.patient_details')),
            ],
        ),
        migrations.AddField(
            model_name='appointment_scheduled',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='blood_request_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_request', models.DateField()),
                ('date_of_response', models.DateField()),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.blood_request')),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor_app.donor_details')),
            ],
        ),
    ]
