# Generated by Django 3.0.5 on 2023-03-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_auto_20230328_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_request',
            name='bg_req',
        ),
    ]
