# Generated by Django 3.0.5 on 2023-03-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_remove_blood_request_bg_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_request_response',
            name='quantity2',
            field=models.IntegerField(default=0),
        ),
    ]
