# Generated by Django 3.0.5 on 2023-03-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_blood_request_response_quantity2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blood_request_response',
            name='quantity2',
        ),
    ]
