# Generated by Django 3.0.5 on 2023-03-31 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0008_auto_20230331_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_request_response',
            name='appointment_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_app.blood_request'),
            preserve_default=False,
        ),
    ]
