# Generated by Django 3.0.5 on 2023-03-31 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0009_donor_details_health'),
        ('home_app', '0009_blood_request_response_appointment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blood_request',
            old_name='hospital_id',
            new_name='hospital_name',
        ),
        migrations.AddField(
            model_name='blood_request',
            name='date_of_response',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='blood_request',
            name='donor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donor_app.donor_details'),
        ),
        migrations.AddField(
            model_name='blood_request',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
