# Generated by Django 3.0.5 on 2023-03-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0011_auto_20230331_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_scheduled',
            name='date_scheduled',
            field=models.DateTimeField(null=True),
        ),
    ]
