# Generated by Django 3.0.5 on 2023-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0012_auto_20230331_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_request',
            name='hospital_add',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
