# Generated by Django 3.0.5 on 2023-04-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0013_blood_request_hospital_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_request_response',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
