# Generated by Django 3.0.5 on 2023-04-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_auto_20230328_1749'),
        ('home_app', '0015_auto_20230404_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='blood_request_response',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_app.patient_details'),
        ),
    ]
