# Generated by Django 3.0.5 on 2023-03-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='dob',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
    ]
