# Generated by Django 3.0.5 on 2023-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_patient_details_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_details',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
