# Generated by Django 3.0.5 on 2023-03-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_patient_details_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.patient_address'),
        ),
    ]
