# Generated by Django 3.0.5 on 2023-04-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0005_auto_20230328_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_address',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='id_no',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
