# Generated by Django 3.0.5 on 2023-04-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0006_auto_20230411_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_address',
            name='patient_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
