# Generated by Django 3.0.5 on 2023-03-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor_address',
            fields=[
                ('donor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('landmark', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='donor_health',
            fields=[
                ('id_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('past_donation', models.CharField(max_length=12)),
                ('hemoglobin_level', models.IntegerField(max_length=5)),
                ('last_piercing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='donor_details',
            fields=[
                ('id_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('contact_no1', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=5)),
                ('location', models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='donor_app.donor_address')),
            ],
        ),
    ]
