# Generated by Django 3.0.5 on 2023-03-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0002_auto_20230327_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_details',
            name='dob',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
        migrations.AddField(
            model_name='donor_health',
            name='last_donation_date',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
    ]
