# Generated by Django 3.0.5 on 2023-03-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0003_auto_20230328_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor_health',
            name='past_donation',
        ),
        migrations.AlterField(
            model_name='donor_health',
            name='hemoglobin_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
