# Generated by Django 3.0.5 on 2023-03-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0004_auto_20230328_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor_health',
            name='last_piercing',
        ),
        migrations.AddField(
            model_name='donor_health',
            name='piercing',
            field=models.BooleanField(default=False),
        ),
    ]
