# Generated by Django 3.0.5 on 2023-03-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0005_auto_20230328_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_details',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
