# Generated by Django 3.0.5 on 2023-03-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0007_auto_20230328_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_health',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
