# Generated by Django 3.0.5 on 2023-03-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0008_auto_20230328_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor_details',
            name='health',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='donor_app.donor_health'),
        ),
    ]
