# Generated by Django 3.0.5 on 2023-04-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0009_donor_details_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_health',
            name='hemoglobin_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
