# Generated by Django 3.0.5 on 2023-04-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0010_auto_20230404_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_details',
            name='id_no',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
