# Generated by Django 3.0.5 on 2023-04-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0011_auto_20230411_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_details',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
