# Generated by Django 3.0.5 on 2023-04-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0012_auto_20230411_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_address',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
