# Generated by Django 3.0.5 on 2023-04-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor_app', '0013_auto_20230411_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_address',
            name='donor_id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor_health',
            name='id_no',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
